[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
rewy_protocol = "BxvZ8gSjCMgKeZ6LLsWX9fGp7A39zLBQ7vcFx91NeNBD"

[programs.devnet]
rewy_protocol = "BxvZ8gSjCMgKeZ6LLsWX9fGp7A39zLBQ7vcFx91NeNBD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
